### ISSUE TITLE
Microscope window is oversized and cannot be resized

### ISSUE THREAD

**Issue by strambc** [WU-BIMAC/4DNMicroscopyMetadataTool#1]
When launching>create new microscope (Tier 1)>use "template_mic_tier5"
The Microscope window that appears cannot be resized and appears truncated

![screen shot 2018-12-01 at 17 48 41](https://user-images.githubusercontent.com/4050585/49333688-5b8f9680-f591-11e8-90e1-7b6082e47f0c.png)

**Comment by strambc** [comment]
When transferring the window to a larger display screen the same size issue persists and there appears to be no way of resizing.

**Comment by Akramhar** [comment]
This should be fixed in the alpha_1
