### ISSUE TITLE
LightSource tier issue: the LightSource type should be present in Tier 1

### ISSUE THREAD

**Issue by strambc** [WU-BIMAC/4DNMicroscopyMetadataTool#5]
LightSource Type: the name of the LightSourceGroup specific Class utilized for this microscope [i.e.
Either one of the following: Laser, Filament, Arc, LightEmittingDiode, (GenericLightSource)] should be available to set in Tier 1 and then it should be used to select the LightSourceGroup sub-class present in subsequent tiers.

**Comment by Akramhar** [comment]
There is no field for Tier 1 in Light Source group so I'm kinda confused by what you are asking here.
I'm going to need more details, maybe we should talk about this?

**Comment by Akramhar** [comment]
should be solved in alpha4
